### PR TITLE
Compatibility with 7.15

### PR DESCRIPTION
**Pull request by cpiment**
Partially solves #197 

I have successfully built the plugin and deployed it in a Kibana 7.15.2 instance. I have noticed that you have rolled back the "build" task of `package.json` to use `../../node_modules/.bin/plugin-helpers`. That script doesn't exist in my environment so I have used `../../scripts/plugins_helpers.js` to build the plugin. How can I do to use the same script as you to build so I don't have to modify the `package.json`?

Regarding the PR, it just changes the way that Angular is initialized inside the plugin. Kibana team has created a `loadAngularBootstrap()` function that has to be called from `vis_controller.ts`.

I hope this helps! If I can do some tests to help you test the plugin please let me know.

### CODE REVIEW

**Comment by fbaligand** [comment]
Hi @cpiment,

Thanks again for your devotion!

As you notice, I change "build" task.
I have to explain : I have a fork kbn-plugin-helpers (from Kibana 7.9) that can build all Kibana versions (before and after Kibana new platform).
And I have a "release-all" shell script that checkout every branch and then call "yarn build" to compile and build the package.
That's why I change the "build" task, that is used in my generic script for all Kibana versions.

That said, you can still build the package using standard Kibana tool, using this task:
`yarn compile-and-build`

So to resume:
compile : generate only target folder
build : generate only the zip package, using existing target folder as input
build-and-compile : compile and generate zip package (using Kibana official tool)

**Comment by fbaligand** [comment]
I just did a complete test session and everything works well!
So I will merge the PR as is.

I also tried the same package for Kibana 7.16, but unfortunately, it doesn't work.
So it seems that there is another migration to do.

So I will create a new 1.12.2 release with Kibana 7.15 support.

Thanks again for your great work!

**Comment by cpiment** [comment]
Thanks @fbaligand! I think that 7.16 is going to be tricky since they have removed the legacy data table plugin in this version from the Kibana codebase... I'll give it a try when I have some time :)

**Comment by fbaligand** [comment]
Ouch…
I dreaded this moment…
Here we are…

As you say, it can be really tricky…

**Comment by fbaligand** [comment]
Concerning Kibana 7.16 support, I think that the best way is to copy/paste "AngularJS integration code" from Kibana 7.15 branch to Enhanced Table code.
More easy to say than to do :)

**Comment by cpiment** [comment]
Hi @fbaligand 

I have had some time to review this. I have seen that all 7.16 versions have this PR merged:

https://github.com/elastic/kibana/pull/115464

I think that means that the Angular dependency is removed from the project, so I think it should be included in the package.json of your plugin, is that right? What do you think?

**Comment by fbaligand** [comment]
Well, if it is necessary, yes.
That said, in a standalone kibana (not dev version), is angularjs module is present in node_modules directory?
If yes, we could just put angularjs as dev dependency in package.json and see if it works as is in a standalone kibana instance

**Pull request merged**
