### PR TITLE
Update handlebars links

### PR DESCRIPTION
**Pull request by nickofthyme**
Handlebars link changed. They had to add `/guide/` for some reason or another!

### CODE REVIEW

**Comment by fbaligand** [comment]
Thanks for the fix!

**Comment by fbaligand** [comment]
@nickofthyme 
Could you also update handlebars link here:
https://github.com/fbaligand/kibana-enhanced-table/blob/master/public/enhanced-table-vis-params.html#L162

Thanks!

**Comment by nickofthyme** [comment]
Sorry, should have checked for more. Fixed!

**Comment by fbaligand** [comment]
Nice!
Don’t be sorry, that’s why review is useful ;)

**Comment by fbaligand** [comment]
LGTM!

**Pull request merged**
